---
title: Indivisible Sebastopol
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  successes:
    title: Successes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    event-start-date: 
    event-end-date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website: 
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image: 
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code: 
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image: 
    mailchimp-form-embed: 
subtitle: 'Hundreds of local citizens working to defend our democracy from Trump''s
  agenda.

'
email: indivisible-wsc@gmail.com
baseurl: 
url: 
twitter_username: "@IndivisibleSeb"
facebook_username: https://www.facebook.com/indivisiblewest/
background-image: "/uploads/16486810_1374718962580538_3407011819369598940_o.jpg"
member-count: 880
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics: 
